name: Update TryHackMe Stats

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch: # allow manual run

jobs:
  update-thm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch TryHackMe stats
        run: |
          USERNAME="lily442"
          API="https://tryhackme.com/api/v2/public-profile?username=${USERNAME}"
          JSON=$(curl -s "$API")

          LEVEL=$(echo "$JSON" | jq -r '.data.level // "N/A"')
          RANK=$(echo "$JSON" | jq -r '.data.rank // "N/A"')
          ROOMS=$(echo "$JSON" | jq -r '.data.completedRoomsNumber // "N/A"')

          echo "### TryHackMe Profile" > thm-stats.md
          echo "[![TryHackMe Badges](https://tryhackme-badges.s3.amazonaws.com/${USERNAME}.png)](https://tryhackme.com/p/${USERNAME})" >> thm-stats.md
          echo "" >> thm-stats.md
          echo "![Level](https://img.shields.io/badge/Level-$LEVEL-blue) ![Rank](https://img.shields.io/badge/Rank-$RANK-green) ![Rooms Completed](https://img.shields.io/badge/Rooms%20Completed-$ROOMS-yellow)" >> thm-stats.md

      - name: Update README with new stats
        run: |
          sed -i '/<!-- THM-STATS:START -->/,/<!-- THM-STATS:END -->/c\<!-- THM-STATS:START -->\n'"$(cat thm-stats.md)"'\n<!-- THM-STATS:END -->' README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update TryHackMe stats" || echo "No changes to commit"
          git push
