name: Update TryHackMe Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-tryhackme-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch TryHackMe stats
        run: |
          curl -s "https://tryhackme-badges.s3.amazonaws.com/lily442.png" -o tryhackme.png

      - name: Create styled badge
        run: |
          convert tryhackme.png -resize 300x300 -bordercolor "#4CAF50" -border 10 styled-tryhackme.png

      - name: Commit and push updated stats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add styled-tryhackme.png
          git commit -m "Update TryHackMe Stats"
          git push
