name: Update TryHackMe Badge

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download TryHackMe Badge
        run: |
          curl -o tryhackme-badge.png "https://tryhackme-badges.s3.amazonaws.com/lily442.png"

      - name: Add badge border styling
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          convert tryhackme-badge.png -bordercolor "#ff4d6d" -border 10x10 tryhackme-badge.png

      - name: Commit and push updated badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tryhackme-badge.png
          git commit -m "Updated TryHackMe badge" || echo "No changes to commit"
          git push
