name: Update TryHackMe Stats

on:
  workflow_dispatch: # Manual trigger from GitHub UI
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch TryHackMe Stats
        run: |
          echo "Fetching: https://tryhackme.com/api/v2/public-profile?username=lily442"
          RESPONSE=$(curl -s "https://tryhackme.com/api/v2/public-profile?username=lily442")
          echo "=== RAW JSON RESPONSE ==="
          echo "$RESPONSE"
          POINTS=$(echo "$RESPONSE" | jq '.data.points // "N/A"')
          RANK=$(echo "$RESPONSE" | jq '.data.rank // "N/A"')
          ROOMS=$(echo "$RESPONSE" | jq '.data.completedRoomsNumber // "N/A"')

          echo "Points: $POINTS | Rank: $RANK | Rooms: $ROOMS" > thm-stats.md

      - name: Update README.md
        run: |
          if grep -q "<!-- THM-STATS:START -->" README.md; then
            sed -i "/<!-- THM-STATS:START -->/,/<!-- THM-STATS:END -->/c\\<!-- THM-STATS:START -->\n$(cat thm-stats.md)\n<!-- THM-STATS:END -->" README.md
          else
            echo -e "\n<!-- THM-STATS:START -->\n$(cat thm-stats.md)\n<!-- THM-STATS:END -->" >> README.md
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update TryHackMe stats" || echo "No changes to commit"
          git push
